Improvements to sentry-gateway
summerwind/alertmanager-sentry-gateway pull request #9
Opened 2020-11-10 18:00 UTC by sagor999

Hi @mikeroll 
here is PR with a list of my changes:
1. switch to go mods and add vendor folder
2. add support for passing any environment into sentry event
3. extract alert severity and pass it to sentry
4. add support for extracting sentry environment from alert label
5. update travis deployment

It is a lot of changes, but 90% of them are due to adding vendor folder.

2020-11-24 20:30 UTC, mikeroll requested changes

2020-11-24 20:30 UTC, mikeroll commented on README.md
> +Go to the [releases page](https://github.com/sagor999/alertmanager-sentry-gateway/releases), find the version you want, and download the tarball file.
If we're to merge this back, we'll need the original username in things like github urls and docker repos.
There's quite a number of such instances but I only mention this once here.

2020-11-24 20:30 UTC, mikeroll commented on .travis.yml
> +  api_key:
Same as with usernames, no need to change this since we're merging back.

2020-11-24 20:30 UTC, mikeroll commented on .travis.yml
>    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
As I understand, `dep` is out of the picture now, so we better remove all mentions of it.

2020-11-29 15:54 UTC, sagor999 commented
I am going to close this PR and re-open another one from a different branch. It will be easier for me to make any fixes that way.

2020-11-29 15:54 UTC, closed without merging